# Variables
@baseUrl = http://localhost:4001/api/v1/levels
@int = {{$randomInt 1000 9999}}
@authToken = {{login.response.body.message}}
@addedlevelId = {{createLevel.response.body.message.id}}

### Get all levels
GET {{baseUrl}}/ HTTP/1.1
Authorization: {{authToken}}

### Add a level
# @name createLevel
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "name": "{{int}}Level",
    "description": "{{int}} level created for test purposes.",
    "access": "0.1.2.3.4.5"
}

### Get level details
GET {{baseUrl}}/{{addedlevelId}}
Authorization: {{authToken}}

### Update Specific level Details
PATCH {{baseUrl}}/{{addedlevelId}} HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "name": "Admin",
    "description": "Updated admin level.",
    "status": false
}

### Delete a specific level
DELETE {{baseUrl}}/{{addedlevelId}} HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

### Bogus Route
GET http://localhost:3000/boguses/ HTTP/1.1

### Post login credentials to get a token
 # @name login
POST http://localhost:4001/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "{{$dotenv DEMO_PASSWORD}}"
}